version: "3"

services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPassword
      - POSTGRES_DB=prisma
