# name: Deploy Stage and run E2E

# on:
#   push:
#     branches:
#       - stage

# jobs:
# Do stuff to run unit tests
#     concurrency:
# group: ${{ github.ref }}
# cancel-in-progress: truecon

# e2e:
#   concurrency:
#     group: ${{ github.ref }}
#     cancel-in-progress: true
#   needs: deploy
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2

#     - name: Cypress run
#       uses: cypress-io/github-action@v2
#       with:
#         working-directory: ./lib/e2e
#         config-file: config.ci.json
