name: Deploy Stage and run E2E

on:
  push:
    branches:
      - stage

jobs:
  # Do stuff to run unit tests
  #     concurrency:
  # group: ${{ github.ref }}
  # cancel-in-progress: truecon
  create-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install pulumi dependencies
        run: cd .pulumi && npm install

      - name: Create resources
        uses: pulumi/actions@v3
        with:
          work-dir: ./.pulumi
          command: up
          stack-name: stage
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{secrets.DIGITALOCEAN_TOKEN}}

  # e2e:
  #   concurrency:
  #     group: ${{ github.ref }}
  #     cancel-in-progress: true
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         working-directory: ./lib/e2e
  #         config-file: config.ci.json
