name: Tear Down Stage

on:
  push:
    branches:
      - master

jobs:
  destroy-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install pulumi dependencies
        uses: pulumi/actions@v3
        with:
          work-dir: ./.pulumi
          command: destroy
          stack-name: stage
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{secrets.DIGITALOCEAN_TOKEN}}
